[terminal.shell]
program = "wsl"
args = [
	"-d",
	"Ubuntu-24.04",
	"--cd",
	"~"
]

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = true
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

# Colors (Tokyo Night)

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'


# Normal colors
[colors.normal]
black   = '#32344a'

red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors

[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'

green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'

[keyboard]
bindings = [{ key = "Space", mods = "Control", chars = "\u0000" },]
